url: "http://blog.wsmelton.info"

title: "Shawn Melton"

description: "Life in the day of PowerShell and SQL Server"

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "wsmelton-git"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-85098649-1"


theme: jekyll-theme-slate