baseURL = "https://wsmelton.github.io/"
title = "Shawn's Notebook"
theme = "temple"
copyright = "(c) 2018 Shawn Melton -- All rights reserved."
googleAnalytics = "UA-85098649-1"

[params]
highlight = true
hjslangs = ["powershell","sql","python","yaml","plaintext","dockerfile"]
topmenu = "categories"

[author]
name = "Shawn Melton"
github = "wsmelton"
twitter = "wsmelton"
linkedin = "wshawnmelton"
